# Generated by Django 4.2.27 on 2026-01-30 01:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('base_image', models.ImageField(blank=True, help_text='Optional base image for img2img', null=True, upload_to='uploaded_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Generation Session',
                'verbose_name_plural': 'Generation Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('model_id', models.CharField(default='stabilityai/stable-diffusion-xl-refiner-1.0', help_text='Hugging Face model ID', max_length=255)),
                ('strength', models.FloatField(default=0.75, help_text='Transformation strength (0.0-1.0). Higher = more change')),
                ('guidance_scale', models.FloatField(default=7.5, help_text='How closely to follow the prompt (1-20)')),
                ('num_inference_steps', models.IntegerField(default=50, help_text='Number of denoising steps (20-100)')),
                ('negative_prompt', models.TextField(blank=True, default='blurry, low quality, distorted, deformed', help_text='What to avoid in generation')),
                ('is_active', models.BooleanField(default=False, help_text='Use this config for next generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Model Configuration',
                'verbose_name_plural': 'Model Configurations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationIteration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iteration_number', models.PositiveIntegerField(default=1)),
                ('prompt', models.TextField(help_text='Description of changes to apply')),
                ('input_image', models.ImageField(blank=True, help_text='Input image for this iteration', null=True, upload_to='generated_images/%Y/%m/')),
                ('output_image', models.ImageField(blank=True, help_text='Generated output image', null=True, upload_to='generated_images/%Y/%m/')),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('generation_time', models.FloatField(blank=True, help_text='Time in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iterations', to='img2img_app.modelconfig')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='img2img_app.generationsession')),
            ],
            options={
                'verbose_name': 'Generation Iteration',
                'verbose_name_plural': 'Generation Iterations',
                'ordering': ['session', 'iteration_number'],
            },
        ),
    ]
