# Generated by Django 4.2.27 on 2026-01-30 01:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('img2img_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Describe the character appearance, style, etc.')),
                ('trigger_word', models.CharField(blank=True, help_text='Optional trigger word to use in prompts (e.g., "CHARNAME")', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='character_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image used as main reference')),
                ('caption', models.CharField(blank=True, help_text='Optional caption describing this specific image', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='img2img_app.character')),
            ],
            options={
                'verbose_name': 'Character Image',
                'verbose_name_plural': 'Character Images',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='generationiteration',
            name='character',
            field=models.ForeignKey(blank=True, help_text='Character used for this generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iterations', to='img2img_app.character'),
        ),
        migrations.AddField(
            model_name='generationsession',
            name='character',
            field=models.ForeignKey(blank=True, help_text='Character to use for consistent generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='img2img_app.character'),
        ),
    ]
