# Generated by Django 4.2.27 on 2026-01-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img2img_app', '0002_character_characterimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='use_refiner',
            field=models.BooleanField(default=False, help_text='Apply SDXL Refiner after SDXL Base for enhanced details'),
        ),
    ]
