# Generated by Django 4.2.27 on 2026-01-31 23:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('img2img_app', '0003_modelconfig_use_refiner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancementJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_variations', models.IntegerField(default=0)),
                ('completed_variations', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhancement_jobs', to='img2img_app.character')),
            ],
            options={
                'verbose_name': 'Enhancement Job',
                'verbose_name_plural': 'Enhancement Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnhancedCharacterImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variation_type', models.CharField(choices=[('front_neutral', 'Front-facing, neutral expression'), ('three_quarter_smile', '3/4 angle, slight smile'), ('side_profile', 'Side profile'), ('different_lighting', 'Different lighting condition')], max_length=30)),
                ('image', models.ImageField(upload_to='enhanced_images/%Y/%m/')),
                ('generation_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_images', to='img2img_app.enhancementjob')),
                ('source_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhancements', to='img2img_app.characterimage')),
            ],
            options={
                'verbose_name': 'Enhanced Character Image',
                'verbose_name_plural': 'Enhanced Character Images',
                'ordering': ['source_image', 'variation_type'],
            },
        ),
        migrations.CreateModel(
            name='CharacterEmbeddingCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(help_text='sdxl or sd15 - determines embedding dimension', max_length=20)),
                ('embedding_file', models.FileField(help_text='Pickled tensor file containing embeddings', upload_to='embeddings_cache/%Y/%m/')),
                ('image_hash', models.CharField(help_text='Hash of all source image paths to detect changes', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_cache', to='img2img_app.character')),
            ],
            options={
                'verbose_name': 'Character Embedding Cache',
                'verbose_name_plural': 'Character Embedding Caches',
            },
        ),
    ]
